### ISSUE TITLE
A mesh for the ground OR a height map.

### ISSUE THREAD

**Issue by Maartenvm** [NLeSC/PattyAnalytics#1]
The visualization team needs a ground layer mesh. 
We can implement this either as a mesh that we load, OR use a shader program that distorts a mesh based on a height map of the ground layer.

Subtasks:
- [ ] Filter out or remove manually; all of the objects in the drive map that are not part of the ground.
- [ ] Grid-ify the result (probably).
- [ ] Make a mesh OR provide a height map with 'sufficient' resolution of the resulting ground, averaging/interpolating non-existant or filtered-out grid points.

If mesh:
- In .obj format. We cannot implement loaders for all different standards, so we've settled on this one.
- Color for the mesh in a texture, please supply .png image.

If height map
- Provide a grayscale 2d image in png format for the heightmap.
- Provide a rgb color image in png format for the color of each point.

**Comment by cwmeijer** [comment]
I never hear Maarten about this anymore and issue is 6 months old.
