### ISSUE TITLE
TestWriteLas might need fixing

### ISSUE THREAD

**Issue by c-martinez** [NLeSC/PattyAnalytics#29]
I'm not 100% sure if `tests.test_conversions.TestWriteLas` properly writes SRS information to header. It might be a local issue with my GDAL, but it would be good if someone can test that headers are being written properly.

**Comment by blootsvoets** [comment]
The test fails here also. Jisk, did you find out if liblas has a method for writing / reading SRS information?

**Comment by jiskattema** [comment]
should be fixed
